### ISSUE TITLE
Scripted-definition of maintuser in RHEL's cloud.cfg is botched.

### ISSUE THREAD

**Issue by ferricoxide** [ferricoxide/AMIgen#26]
CentOS AMIs properly receive the following default user stanza:

```
  default_user:
    name: maintuser
    lock_passwd: true
    gecos: Maintenance User
    groups: [wheel, adm]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
```

Need to fix scripts to ensure that RHEL AMIs get same stanza.
